[build]
  publish = "."

# Ensure site is accessible to crawlers
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=UTF-8"
    
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"

# Redirect spam but allow all real content
[[redirects]]
  from = "/tinggi/*"
  to = "/404.html"
  status = 404
  force = true
